import type { Project } from "@/types";

export const voxelProject: Project = {
  id: "voxel-project",
  title: "Voxel Engine: High-Performance C++20 Game Engine",
  description:
    "A modern, from-scratch voxel game engine featuring infinite procedural terrain, dynamic lighting, weather systems, and multithreaded chunk generation with OpenGL 4.6.",
  descriptionSv:
    "En modern voxelmotormotor byggd från grunden med oändlig procedurell terräng, dynamisk belysning, vädersystem och flertrådig chunk-generering med OpenGL 4.6.",
  technologies: [
    "C++20",
    "OpenGL 4.6",
    "CMake 3.28+",
    "GLFW 3.4",
    "GLM 1.0.1",
    "FastNoiseLite 1.1.1",
    "stb_image",
    "nlohmann/json",
    "BS::thread_pool",
    "Google Test",
  ],
  link: "https://github.com/Berkay2002/voxel-project",
  githubLink: "https://github.com/Berkay2002/voxel-project",
  image: "demo/demo_surface.gif",
  imageAlt: "Voxel Engine surface exploration with procedural terrain",
  detailedDescription:
    "A high-performance voxel game engine built from scratch using modern C++20, inspired by Minecraft. The engine features a modular architecture with core subsystems (graphics, rendering, scene, atmosphere, settings) decoupled from game logic. It uses OpenGL 4.6 Core Profile with aggressive face culling, frustum culling, and multithreaded chunk generation. The world system generates infinite procedural terrain using 3D Perlin Noise with biome transitions, spaghetti cave systems with natural water flooding, and destructible terrain via raycast-based block interactions. Rendering includes a dynamic day/night cycle with lunar phases, directional lighting with per-vertex ambient occlusion, screen-space ambient occlusion (SSAO), shadow mapping with cascades, transparent water, volumetric clouds, distance fog, and a weather system with rain/snow particles. The engine is registry-driven for blocks and textures, uses centralized configuration, and implements async chunk loading with BS::thread_pool for background generation while maintaining GPU uploads on the main thread.",
  detailedDescriptionSv:
    "En högpresterande voxelmotormotor byggd från grunden med modern C++20, inspirerad av Minecraft. Motorn har en modulär arkitektur med kärnsystem (grafik, rendering, scen, atmosfär, inställningar) frikopplade från spellogik. Den använder OpenGL 4.6 Core Profile med aggressiv ytkullning, frustumkullning och flertrådig chunk-generering. Världssystemet genererar oändlig procedurell terräng med 3D Perlin-brus och biomövergångar, spaghetti-grottsystem med naturlig vattenöversvämning och destruerbar terräng via raycast-baserad blockinteraktion. Rendering inkluderar dynamisk dag/natt-cykel med månfaser, riktad belysning med ambient ocklusion per vertex, screen-space ambient occlusion (SSAO), shadow mapping med kaskader, transparent vatten, volymetriska moln, distansdimma och ett vädersystem med regn/snöpartiklar. Motorn är registerstyrd för block och texturer, använder centraliserad konfiguration och implementerar asynkron chunk-laddning med BS::thread_pool för bakgrundsgenerering samtidigt som GPU-uppladdningar sker på huvudtråden.",
  features: [
    "Modern C++20 architecture with modular design (core/, world/, ui/ subdirectories)",
    "High-performance OpenGL 4.6 rendering with aggressive face culling and frustum culling",
    "Multithreaded chunk generation and meshing using BS::thread_pool",
    "Infinite procedural terrain with 3D Perlin Noise (FastNoiseLite) and biome system (Plains, Mountains)",
    "Spaghetti cave systems with natural entrances and water flooding",
    "Destructible terrain with raycast-based (DDA algorithm) block breaking and placing",
    "Dynamic day/night cycle with sun/moon and lunar phases",
    "Advanced lighting: directional lighting, per-vertex AO, SSAO, shadow mapping with cascades",
    "Transparent water rendering with proper blending",
    "Volumetric clouds (Fast 2D / Fancy 3D modes)",
    "Distance fog for atmospheric depth",
    "Weather system with rain/snow particles respecting per-chunk heightmaps",
    "Registry-driven blocks and textures loaded from JSON configuration",
    "Centralized configuration system (WorldConfig, GameConfig)",
    "Comprehensive test suite with Google Test covering ray calculations, chunk storage, heightmaps, and voxel raycasting",
  ],
  featuresSv: [
    "Modern C++20-arkitektur med modulär design (core/, world/, ui/ underkataloger)",
    "Högpresterande OpenGL 4.6-rendering med aggressiv ytkullning och frustumkullning",
    "Flertrådig chunk-generering och meshing med BS::thread_pool",
    "Oändlig procedurell terräng med 3D Perlin-brus (FastNoiseLite) och biomsystem (Slätt, Berg)",
    "Spaghetti-grottsystem med naturliga ingångar och vattenöversvämning",
    "Destruerbar terräng med raycast-baserad (DDA-algoritm) blockbrytning och placering",
    "Dynamisk dag/natt-cykel med sol/måne och månfaser",
    "Avancerad belysning: riktad belysning, AO per vertex, SSAO, shadow mapping med kaskader",
    "Transparent vattenrendering med korrekt blandning",
    "Volymetriska moln (Snabb 2D / Fancy 3D-lägen)",
    "Distansdimma för atmosfäriskt djup",
    "Vädersystem med regn/snöpartiklar som respekterar höjdkartor per chunk",
    "Registerstyrd block- och texturhantering laddad från JSON-konfiguration",
    "Centraliserat konfigurationssystem (WorldConfig, GameConfig)",
    "Omfattande testsvit med Google Test som täcker strålberäkningar, chunk-lagring, höjdkartor och voxel-raycasting",
  ],
  challenges: [
    "Achieving high performance with infinite procedural terrain generation while maintaining 60+ FPS",
    "Implementing aggressive face culling to avoid rendering internal/hidden block faces",
    "Managing multithreaded chunk generation and meshing without blocking the main render thread",
    "Coordinating async chunk loading with GPU uploads on the main thread (avoiding GL context issues)",
    "Creating realistic cave systems with natural entrances and proper water flooding mechanics",
    "Implementing screen-space ambient occlusion (SSAO) with proper kernel generation and uniform caching",
    "Rendering transparent water with correct depth sorting and blending",
    "Synchronizing weather particle spawning with per-chunk heightmaps for accurate placement",
  ],
  challengesSv: [
    "Uppnå hög prestanda med oändlig procedurell terränggenerering samtidigt som 60+ FPS bibehålls",
    "Implementera aggressiv ytkullning för att undvika rendering av interna/dolda blockytor",
    "Hantera flertrådig chunk-generering och meshing utan att blockera huvudrenderingstråden",
    "Koordinera asynkron chunk-laddning med GPU-uppladdningar på huvudtråden (undvika GL-kontextproblem)",
    "Skapa realistiska grottsystem med naturliga ingångar och korrekt vattenöversvämningsmekanik",
    "Implementera screen-space ambient occlusion (SSAO) med korrekt kernel-generering och uniform-cachning",
    "Rendera transparent vatten med korrekt djupsortering och blandning",
    "Synkronisera väderspartikelskapande med höjdkartor per chunk för korrekt placering",
  ],
  solution:
    "The engine uses a modular architecture with core subsystems decoupled from game logic. Multithreaded chunk generation runs on BS::thread_pool in the background, with mesh building returning separate opaque/water meshes. GPU uploads are capped per frame and executed only on the main thread via ProcessPendingMeshes in ChunkManager. Aggressive face culling is implemented in ChunkMeshBuilder by checking neighboring blocks before adding faces. The registry-driven approach loads blocks and textures from JSON configuration files, centralizing tunables in WorldConfig/GameConfig. Cave generation uses SpaghettiCaveCarver with biome-aware noise, and weather particles respect per-chunk heightmaps from ChunkManager. SSAO uses precomputed kernel UBO with cached uniform locations for efficiency. The render pipeline processes opaque → water → outlines → sky/weather passes in sequence, driven by the main loop in Application.h.",
  solutionSv:
    "Motorn använder en modulär arkitektur med kärnsystem frikopplade från spellogik. Flertrådig chunk-generering körs på BS::thread_pool i bakgrunden, med mesh-byggande som returnerar separata opaka/vatten-meshes. GPU-uppladdningar är begränsade per frame och körs endast på huvudtråden via ProcessPendingMeshes i ChunkManager. Aggressiv ytkullning implementeras i ChunkMeshBuilder genom att kontrollera närliggande block innan ytor läggs till. Den registerstyrda metoden laddar block och texturer från JSON-konfigurationsfiler och centraliserar justeringsbara parametrar i WorldConfig/GameConfig. Grottgenerering använder SpaghettiCaveCarver med biommedvetet brus, och väderpartiklar respekterar höjdkartor per chunk från ChunkManager. SSAO använder förgenererad kernel UBO med cachade uniform-platser för effektivitet. Renderingspipelinen bearbetar opak → vatten → konturer → himmel/väder-pass i sekvens, driven av huvudloopen i Application.h.",
  outcome:
    "The voxel engine delivers smooth 60+ FPS gameplay with infinite procedural terrain generation, realistic cave systems, and immersive weather/lighting effects. The modular C++20 architecture ensures clean separation between engine core and game logic, making the codebase maintainable and extensible. Multithreaded chunk generation with capped GPU uploads prevents frame drops, while aggressive face culling significantly reduces vertex count. The registry-driven configuration allows easy content creation and tuning. Comprehensive automated tests using Google Test ensure reliability across ray calculations, chunk storage, heightmaps, block registry, and voxel raycasting. The engine successfully demonstrates modern graphics techniques including SSAO, shadow mapping, volumetric clouds, and transparent water rendering, all running on OpenGL 4.6 Core Profile.",
  outcomeSv:
    "Voxelmotorn levererar smidigt 60+ FPS-spelande med oändlig procedurell terränggenerering, realistiska grottsystem och uppslukande väder-/belysningseffekter. Den modulära C++20-arkitekturen säkerställer ren separation mellan motorkärnan och spellogiken, vilket gör kodbasen underhållbar och utbyggbar. Flertrådig chunk-generering med begränsade GPU-uppladdningar förhindrar frame-dropp, medan aggressiv ytkullning avsevärt minskar vertex-antal. Den registerstyrda konfigurationen möjliggör enkel innehållsskapande och justering. Omfattande automatiserade tester med Google Test säkerställer tillförlitlighet över strålberäkningar, chunk-lagring, höjdkartor, blockregister och voxel-raycasting. Motorn demonstrerar framgångsrikt moderna grafiktekniker inklusive SSAO, shadow mapping, volymetriska moln och transparent vattenrendering, allt körande på OpenGL 4.6 Core Profile.",
  gallery: [
    {
      image: "demo/demo_surface.gif",
      alt: "Voxel Engine surface exploration showing procedural terrain with biomes",
      caption: "Surface exploration with procedural terrain generation and biome transitions",
      captionSv: "Ytutforskning med procedurell terränggenerering och biomövergångar",
    },
    {
      image: "demo/demo_caves.gif",
      alt: "Voxel Engine cave systems with natural water flooding",
      caption: "Spaghetti cave systems with natural entrances and water flooding",
      captionSv: "Spaghetti-grottsystem med naturliga ingångar och vattenöversvämning",
    },
    {
      image: "demo/demo.gif",
      alt: "Voxel Engine general gameplay demonstration",
      caption: "General gameplay showcasing terrain, lighting, and block interactions",
      captionSv: "Allmänt spelande som visar terräng, belysning och blockinteraktioner",
    },
    {
      image: "demo/demo.mp4",
      alt: "Voxel Engine video demonstration",
      caption: "Full video demonstration of engine features and capabilities",
      captionSv: "Fullständig videodemonstration av motorfunktioner och kapaciteter",
    },
    {
      image: "demo/2026-01-04 16-26-56.mkv",
      alt: "Voxel Engine extended gameplay recording",
      caption: "Extended gameplay recording showcasing all major features",
      captionSv: "Utökad spelupptagning som visar alla huvudfunktioner",
    },
  ],
};
